name: Actualizar progreso de traducción

on:
  push:
    paths:
      - 'files/*.rpy'
      - 'translation_progress.py'

jobs:
  scan-translation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0
      - name: Instalar Python
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
      - name: Ejecutar script de progreso
        run: python3 translation_progress.py
      - name: Configurar git
        run: |
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Commit y push
        run: |
          git add TRANSLATION_PROGRESS.md README.md
          git commit -m "Actualiza progreso de traducción" || echo "Sin cambios"
          git pull --rebase origin main
          git push origin HEAD:main